{
  description = "Bearded NAS — NixOS configuration for young (TerraMaster F4-245 NAS)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    impermanence.url = "github:nix-community/impermanence";
  };

  outputs = { self, nixpkgs, disko, impermanence, ... }:
    let
      system = "x86_64-linux";
      vars = import ./variables.nix;
      hostDir = ./hosts + "/${vars.mySystem.manufacturer}/${vars.mySystem.model}";
    in
    {
      # Attribute name follows variables.nix's own hostName rather than
      # being hardcoded — today that's still "young" (zero change to the
      # real deployment), but it also means a differently-named instance
      # (e.g. one freshly generated by hosts/installer/wizard, which
      # writes its own variables.nix into its own checkout) gets a
      # matching `nixosConfigurations.<hostname>` automatically, with no
      # flake.nix edit needed. Still only one buildable instance per
      # checkout at a time — see docs/ARCHITECTURE.md's variables.nix
      # section for what true multi-instance support would still need.
      nixosConfigurations.${vars.networking.hostName} = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          disko.nixosModules.disko
          impermanence.nixosModules.impermanence
          (hostDir + "/disko.nix")
          (hostDir + "/configuration.nix")
          ./variables.nix
          ./modules/common.nix
          ./modules/users.nix
          ./modules/zfs.nix
          ./modules/samba.nix
          ./modules/nfs.nix
          ./modules/media-stack.nix
          ./modules/nebula.nix
          ./modules/traefik.nix
          ./modules/dashboard.nix
          ./modules/frigate.nix
          ./modules/home-assistant.nix
          ./modules/minio.nix
          ./modules/filebrowser.nix
          ./modules/self-update.nix
          ./modules/lldap.nix
          ./modules/authelia.nix
          ./modules/smtp-relay.nix
          ./modules/dashboard-login.nix
          ./modules/unix-ldap-login.nix
        ];
      };

      nixosConfigurations.installer = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit self disko; };
        modules = [
          disko.nixosModules.disko
          ./hosts/installer/configuration.nix
        ];
      };
    };
}
