{
  description = "Bearded NAS — NixOS configuration for young (TerraMaster F4-245 NAS)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    impermanence.url = "github:nix-community/impermanence";
  };

  outputs = { self, nixpkgs, disko, impermanence, ... }:
    let
      system = "x86_64-linux";
      vars = import ./variables.nix;
      hostDir = ./hosts + "/${vars.mySystem.manufacturer}/${vars.mySystem.model}";

      # Dashboard-driven service enable/disable toggles
      # (modules/dashboard-services.nix) write here on save — a real
      # path on disk, independent of which checkout is doing the
      # building, so it survives both a manual rebuild and every future
      # self-update fetch (which always re-extracts a fresh tarball that
      # never saw a local variables.nix edit). A no-op import on any box
      # that's never touched that feature.
      serviceOverridesPath = /persist/nixos-service-overrides.nix;
      # Same shape, for modules/dashboard-network.nix's DHCP/Static IP
      # toggle.
      networkOverridesPath = /persist/nixos-network-overrides.nix;
      # Same shape, for modules/dashboard-smtp.nix's SMTP relay settings
      # (forces mySystem.smtp as a whole — the password itself lives in
      # /persist/etc/opensmtpd/secrets, not here).
      smtpOverridesPath = /persist/nixos-smtp-overrides.nix;
      # Same shape, for modules/dashboard-svcconfig.nix's Authelia theme
      # setting (the only Service Configuration field that needs a
      # rebuild — MinIO's root credentials are a plain runtime file, no
      # overrides path needed for those).
      autheliaOverridesPath = /persist/nixos-authelia-overrides.nix;
      # Same shape, for modules/dashboard-svcconfig.nix's Vaultwarden
      # signupsAllowed setting.
      vaultwardenOverridesPath = /persist/nixos-vaultwarden-overrides.nix;
      # Same shape, for modules/dashboard-svcconfig.nix's Tailscale
      # acceptDns/acceptRoutes/advertiseExitNode/advertiseRoutes
      # settings.
      tailscaleOverridesPath = /persist/nixos-tailscale-overrides.nix;
    in
    {
      # Attribute name follows variables.nix's own hostName rather than
      # being hardcoded — today that's still "young" (zero change to the
      # real deployment), but it also means a differently-named instance
      # (e.g. one freshly generated by hosts/installer/wizard, which
      # writes its own variables.nix into its own checkout) gets a
      # matching `nixosConfigurations.<hostname>` automatically, with no
      # flake.nix edit needed. Still only one buildable instance per
      # checkout at a time — see docs/ARCHITECTURE.md's variables.nix
      # section for what true multi-instance support would still need.
      nixosConfigurations.${vars.networking.hostName} = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          disko.nixosModules.disko
          impermanence.nixosModules.impermanence
          (hostDir + "/disko.nix")
          (hostDir + "/configuration.nix")
          ./variables.nix
          ./modules/common.nix
          ./modules/users.nix
          ./modules/zfs.nix
          ./modules/samba.nix
          ./modules/nfs.nix
          ./modules/media-stack.nix
          ./modules/nebula.nix
          ./modules/traefik.nix
          ./modules/traefik-dns01.nix
          ./modules/dashboard.nix
          ./modules/dashboard-services.nix
          ./modules/dashboard-network.nix
          ./modules/dashboard-smtp.nix
          ./modules/dashboard-nebula.nix
          ./modules/dashboard-svcconfig.nix
          ./modules/vaultwarden.nix
          ./modules/scrutiny.nix
          ./modules/plex.nix
          ./modules/tailscale.nix
          ./modules/dashboard-tailscale.nix
          ./modules/system-rebuild.nix
          ./modules/frigate.nix
          ./modules/home-assistant.nix
          ./modules/minio.nix
          ./modules/filebrowser.nix
          ./modules/self-update.nix
          ./modules/lldap.nix
          ./modules/authelia.nix
          ./modules/smtp-relay.nix
          ./modules/dashboard-login.nix
          ./modules/unix-ldap-login.nix
        ] ++ (if builtins.pathExists serviceOverridesPath then [ serviceOverridesPath ] else [ ])
          ++ (if builtins.pathExists networkOverridesPath then [ networkOverridesPath ] else [ ])
          ++ (if builtins.pathExists smtpOverridesPath then [ smtpOverridesPath ] else [ ])
          ++ (if builtins.pathExists autheliaOverridesPath then [ autheliaOverridesPath ] else [ ])
          ++ (if builtins.pathExists vaultwardenOverridesPath then [ vaultwardenOverridesPath ] else [ ])
          ++ (if builtins.pathExists tailscaleOverridesPath then [ tailscaleOverridesPath ] else [ ]);
      };

      nixosConfigurations.installer = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit self disko; };
        modules = [
          disko.nixosModules.disko
          ./hosts/installer/configuration.nix
        ];
      };
    };
}
